import {
  BadgeIndianRupee,
  BarChart3,
  Bell,
  Building2,
  CalendarClock,
  CalendarDays,
  ClipboardCheck,
  FileClock,
  FileSignature,
  FolderKanban,
  FolderLock,
  GitPullRequestArrow,
  Inbox,
  LayoutDashboard,
  LifeBuoy,
  LineChart,
  Megaphone,
  Palmtree,
  ReceiptText,
  ScrollText,
  Settings,
  ShieldCheck,
  Sparkles,
  Target,
  Timer,
  Users,
  UsersRound,
  Video,
  type LucideIcon,
} from 'lucide-react';

/** Serializable icon keys so server-built nav can cross into client components. */
export const NAV_ICONS = {
  dashboard: LayoutDashboard,
  calendar: CalendarDays,
  bell: Bell,
  projects: FolderKanban,
  tasks: ClipboardCheck,
  meetings: Video,
  documents: FolderLock,
  tickets: LifeBuoy,
  clients: Building2,
  company: Building2,
  leads: Target,
  invoices: ReceiptText,
  requests: Inbox,
  security: ShieldCheck,
  reports: LineChart,
  team: UsersRound,
  leave: Palmtree,
  announcements: Megaphone,
  changes: GitPullRequestArrow,
  audit: FileClock,
  settings: Settings,
  users: Users,
  proposals: FileSignature,
  contracts: ScrollText,
  time: Timer,
  profitability: BadgeIndianRupee,
  analytics: BarChart3,
  renewals: CalendarClock,
  assistant: Sparkles,
} satisfies Record<string, LucideIcon>;

export type NavIconKey = keyof typeof NAV_ICONS;
